# Use an official Node.js runtime as a parent image
FROM node:18

# Set the working directory inside the container
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install project dependencies
RUN npm i

EXPOSE 5173

# Start the Vite development server
CMD ["npm", "run", "dev"]
