version: '3'
services:
  mysql:
    build:
      context: db
      dockerfile: Dockerfile.mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 1s
      retries: 20

  node-app:
    build:
      context: server
      dockerfile: Dockerfile.node
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://node-app:3000/health"]
      interval: 10s
      timeout: 1s
      retries: 20

  react-app:
    build:
      context: client
      dockerfile: Dockerfile.react
    ports:
      - "3001:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://react-app/"]
      interval: 10s
      timeout: 1s
      retries: 20

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      node-app:
        condition: service_healthy
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl