version: '3'
services:
  node-app:
    build:
      context: server
      dockerfile: Dockerfile.node
    volumes:
      - ./server/config:/app/config
      - ./server/controllers:/app/controllers
      - ./server/middleware:/app/middleware
      - ./server/models:/app/models
      - ./server/routes:/app/routes
      - ./server/uploads:/app/uploads
      - ./server/app.js:/app/app.js

  react-app:
    build:
      context: client
      dockerfile: Dockerfile.react
    volumes:
      - ./client/public:/app/public
      - ./client/src:/app/src
      - ./client/index.html:/app/index.html
      - ./client/vite.config.js:/app/vite.config.js

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl