version: '3'
services:
  node-app:
    build:
      context: server
      dockerfile: Dockerfile.node

  nginx:
    build:
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl