# Use an official Nginx image as a parent image
FROM nginx:stable

# Copy custom Nginx configuration files to the container
COPY ./nginx.conf /etc/nginx/nginx.conf

# Copy SSL certificates (if needed)
COPY ./ssl /etc/nginx/ssl

# Expose ports 80 (HTTP) and 443 (HTTPS)
EXPOSE 80
EXPOSE 443

# Nginx is automatically started by the base image
